### ISSUE TITLE
Disallow plugins named "contest"

### ISSUE THREAD

**Issue by insomniacslk** [facebookincubator/contest#10]
We are going to use plugin names for event namespaces, and "contest" is going to be a reserved name for the framework itself

**Comment by xaionaro** [comment]
If I understand correctly the task then it could be implemented as an additional check here:

https://github.com/facebookincubator/contest/pull/60/files#diff-84f3bd06e0d39e53607b8726fc4ec61fR15

**Comment by xaionaro** [comment]
The draft is in PR#64
