### ISSUE TITLE
Add YAML config adapter

### ISSUE THREAD

**Issue by insomniacslk** [facebookincubator/contest#114]
This has been floating around in my mind for a long time - YAML is more flexible and expressive than JSON, and it would simplify the generation of more complex job descriptors. A nice way to do that in my opinion is using something similar to Caddy's config adapters, https://caddyserver.com/docs/config-adapters . At a quick look I am not sure if we can easily reuse Caddy's adapters code though - otherwise we will probably roll out our own. CC @mholt for advice on this, if you have time :)

**Comment by mholt** [comment]
The YAML adapter is just a few lines - a lib to read in YAML as a generic structure and then a call to encode it as JSON.

**Comment by insomniacslk** [comment]
Thank you @mholt - and you didn't see any issue in mapping any YAML to JSON in general, or that observation is limited to the way JSON and YAML are used in Caddy?

**Comment by mholt** [comment]
I don't actually use YAML myself, but I haven't heard any issues reported, either. I assume that any of the advanced features of YAML would be "unrolled" into a typical K/V structure that is compatible with JSON. I'm _sure_ there is a way to break the conversion but hopefully only with crazy/convoluted uses of YAML.

**Comment by insomniacslk** [comment]
good to know, thanks a lot for your input Matt!
