### ISSUE TITLE
Switch to YAML

### ISSUE THREAD

**Issue by insomniacslk** [facebookincubator/contest#120]
As discussed in https://github.com/facebookincubator/contest/pull/117 and in https://eli.thegreenplace.net/2008/11/22/json-yaml-but-yaml-json , JSON is (should be?) a subset of YAML, and since YAML is way more flexible, we could switch to it entirely. CC @xaionaro

**Comment by tfg13** [comment]
Do we still want to do this? We support YAML job descriptors, which is the most user facing part.
Reasons to not go further:
- YAML has its own problems
- We actually operate direction on JSON in some DB queries, this wouldn't work with YAML

I think this can be closed
