### ISSUE TITLE
Final Reporters not registered

### ISSUE THREAD

**Issue by walterchris** [facebookincubator/contest#164]
Hi,
I do not see the ability to register FinalReporters here. I do see that the Reports do run, but FinalReporters do not run. We could either iterate over reporters again and run FinalReport, or register FinalReporters itself. What do you think?

My suggestion would be to iterate over reporters again. So Replacing:

`for _, bundle := range j.FinalReporterBundles {`

with

`for _, bundle := range j.RunReporterBundles {`

**Comment by insomniacslk** [comment]
Reporters are of only one type, that is `job.Reporter` (see https://github.com/facebookincubator/contest/blob/master/pkg/job/reporting.go#L45 ).

`job.Reporter` already embeds both concepts of run reporter and final reporter, so there is no need to register them separately explicitly. It is sufficient to call `Load` on the reporter implementation to get both (if supported), as you can see at https://github.com/facebookincubator/contest/blob/master/cmds/contest/main.go#L70 .

Every reporter then decides whether it supports run reporting, final reporting, or both, and if called it will behave accordingly. A way to signal that one type of reporting is not supported is to return an error in either `ValidateRunParameters` or `ValidateFinalParameters` - these two functions are only called if the corresponding type (run or final) of reporting is requested in the job description.

Am I answering the right question or it was completely different? :-)

**Comment by insomniacslk** [comment]
Reporters are of only one type, that is `job.Reporter` (see https://github.com/facebookincubator/contest/blob/master/pkg/job/reporting.go#L45 ).

`job.Reporter` already embeds both concepts of run reporter and final reporter, so there is no need to register them separately explicitly. It is sufficient to call `Load` on the reporter implementation to get both (if supported), as you can see at https://github.com/facebookincubator/contest/blob/master/cmds/contest/main.go#L70 .

Every reporter then decides whether it supports run reporting, final reporting, or both, and if called it will behave accordingly. A way to signal that one type of reporting is not supported is to return an error in either `ValidateRunParameters` or `ValidateFinalParameters` - these two functions are only called if the corresponding type (run or final) of reporting is requested in the job description.

Am I answering the right question or it was completely different? :-)

**Comment by walterchris** [comment]
No you are right. I did not understand that I have to add "FinalReporters" to the Reporting section in order to enable the `FinalRunReport` . Sorry for the confusing though and thanks for clearing that up for me :)
