### ISSUE TITLE
Improve error reporting when TestStep tries to emit an event which is not allowed

### ISSUE THREAD

**Issue by marcoguerri** [facebookincubator/contest#24]
When a TestStep tries to emit and event which is not allowed, the emitter fails with a generic error. It should be more specific and give pointers to be able to identify which TestStep actually failed. I have a refactor of the events emission control path ready, so this issue should be addressed there.

**Comment by xaionaro** [comment]
Khm. How to reproduce this? I've just made a quick look and I see no event name checks at all at the moment.

Event is just added (and then flushed):
```go
	r.frameworkEventsLock.Lock()
	r.buffFrameworkEvents = append(r.buffFrameworkEvents, event)
	if len(r.buffFrameworkEvents) >= r.frameworkEventsFlushSize {
		doFlush = true
	}
	r.frameworkEventsLock.Unlock()
```
