### ISSUE TITLE
Invoking JobManager from a Reporter plugin

### ISSUE THREAD

**Issue by llogen** [facebookincubator/contest#273]
Hello,
i am writing on an own reporter plugin and i wonder if there is a possibility to invoke the JobManager from the reporter plugin. I studied the architecture and found no way to realize this. That would be great to fetch more data within the reporter, to make the reporter more flexible in his actions. Maybe there is already a way to do this and you could tell me.
Best regards llogen

**Comment by tfg13** [comment]
Yeah this is not really possible at the moment. Can you elaborate a bit more on what you are trying to do, what kind of data are you trying to pull into the reporter?

**Comment by llogen** [comment]
I want to invoke the GetJobReport function to get access to the full report. That would be great, to do some more computations in the reporter plugin based on this data.

**Comment by tfg13** [comment]
Ah do you mean reading report data from other/previous jobs?

We currently don't allow this on purpose to keep the jobs independent.

**Comment by llogen** [comment]
Yes or reading the report meta data from the same job. Would be great to get such a feature.
Best regards llogen

**Comment by llogen** [comment]
Thank you very much!
