### ISSUE TITLE
mysql locking

### ISSUE THREAD

**Issue by pmazzini** [facebookincubator/contest#35]
* make locking mechanism configurable

**Comment by xaionaro** [comment]
Am I understand correctly that it's just required to implement MySQL-based target locker and to allow use it by JobRunner?

**Comment by pmazzini** [comment]
Yes, that is correct.

**Comment by pmazzini** [comment]
Related PRs #36 #44 

@xaionaro Feel free to grab it if you want.

**Comment by tfg13** [comment]
This was done, the dblocker is available and works, we use it a lot. I'll revive #140 to make it default
