### ISSUE TITLE
Integrate ConTest with GitHub

### ISSUE THREAD

**Issue by insomniacslk** [facebookincubator/contest#38]
This is already partially implemented. Requires a github bot that needs to be hosted somewhere, and installed on the repo.

**Comment by xaionaro** [comment]
Could you clarify what is required in this task? Am I understand correctly that it's required to integrate ConTest with GitHub's PR flow?

**Comment by tfg13** [comment]
Is this still relevant? I think we have a ton of integration by now. What is missing :)

**Comment by insomniacslk** [comment]
This was meant to enable a github integration similar to how CircleCI and Travis-CI work, so that people could install it and run ConTest from their GitHub reopositories, and test on physical/virtual hardware. However with GitHub Actions this is not relevant anymore
