### ISSUE TITLE
[discussion] Instead of implementing different lockers, implement different storages

### ISSUE THREAD

**Issue by xaionaro** [facebookincubator/contest#57]
I have no opinion here, yet. It's just a thought :)

For example we will decide to add a support of "PostgreSQL". We will implement it in both places: `plugins/storage` and `plugins/targetlocker`. And the same will happen to any new storage (Sybase, redis, whatever). So it seems like a `storage` just should support `targetlocker` routines and we need to implement only the unite `targetlocker/builtin` (which will utilize those routines) instead of separate `targetlocker/inmemory`, `targetlocker/mysql`, `targetlocker/postgresql` etc.

What are your thought on this?

Related: https://github.com/facebookincubator/contest/issues/35

**Comment by marcoguerri** [comment]
I think the rationale here was that we did not want to force the storage interface to implement locking, as in most of the cases locking would be done with a backend/service that is different from the data backend. 

Off the top of my head I think the two interfaces should be separate, and `RDBMS` plugin might implement both interfaces. But I wouldn't merge the target locking interface in the storage interface.

**Comment by xaionaro** [comment]
Sounds reasonable.
