### ISSUE TITLE
Write CLI for further analysis of job events

### ISSUE THREAD

**Issue by insomniacslk** [facebookincubator/contest#9]
We want a CLI with a more powerful query syntax (`jq`-like) on top of the `[]Event` returned by the ConTest API. This will allow actions like "get all the events in this time range and/or for these jobs, via API, then apply further filtering with another query language" (e.g. using jq on a JSON generated from the event list).

For the name, I suggest `conquer` (i.e. Contest Query) :)

**Comment by xaionaro** [comment]
To do not re-invent a `jq` is it possible to provide an example how an execution (and output) of this tool should look like? :)
